name: Annoq TopMed Data

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: es01
    mem_limit: 18g
    cpus: 2.0
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03,es04,es05,es06,es07,es08,es09,es10
      - cluster.initial_master_nodes=es01,es02,es03,es04,es05,es06,es07,es08,es09,es10
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: es02
    mem_limit: 18g
    cpus: 2.0
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03,es04,es05,es06,es07,es08,es09,es10
      - cluster.initial_master_nodes=es01,es02,es03,es04,es05,es06,es07,es08,es09,es10
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: es03
    mem_limit: 18g
    cpus: 2.0
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es04,es05,es06,es07,es08,es09,es10
      - cluster.initial_master_nodes=es01,es02,es03,es04,es05,es06,es07,es08,es09,es10
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic
  

  es04:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: es04
    mem_limit: 18g
    cpus: 2.0
    environment:
      - node.name=es04
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es03,es05,es06,es07,es08,es09,es10
      - cluster.initial_master_nodes=es01,es02,es03,es04,es05,es06,es07,es08,es09,es10
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data04:/usr/share/elasticsearch/data
    networks:
      - elastic

  es05:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: es05
    mem_limit: 18g
    cpus: 2.0
    environment:
      - node.name=es05
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es03,es04,es06,es07,es08,es09,es10
      - cluster.initial_master_nodes=es01,es02,es03,es04,es05,es06,es07,es08,es09,es10
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data05:/usr/share/elasticsearch/data
    networks:
      - elastic   


  es06:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: es06
    mem_limit: 18g
    cpus: 2.0
    environment:
      - node.name=es06
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es03,es04,es05,es07,es08,es09,es10
      - cluster.initial_master_nodes=es01,es02,es03,es04,es05,es06,es07,es08,es09,es10
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data06:/usr/share/elasticsearch/data
    networks:
      - elastic       


  es07:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: es07
    mem_limit: 18g
    cpus: 2.0
    environment:
      - node.name=es07
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es03,es04,es05,es06,es08,es09,es10
      - cluster.initial_master_nodes=es01,es02,es03,es04,es05,es06,es07,es08,es09,es10
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data07:/usr/share/elasticsearch/data
    networks:
      - elastic         


  es08:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: es08
    mem_limit: 18g
    cpus: 2.0
    environment:
      - node.name=es08
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es03,es04,es05,es06,es07,es09,es10
      - cluster.initial_master_nodes=es01,es02,es03,es04,es05,es06,es07,es08,es09,es10
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data08:/usr/share/elasticsearch/data
    networks:
      - elastic          


  es09:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: es09
    mem_limit: 18g
    cpus: 2.0
    environment:
      - node.name=es09
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es03,es04,es05,es06,es07,es08,es10
      - cluster.initial_master_nodes=es01,es02,es03,es04,es05,es06,es07,es08,es09,es10
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data09:/usr/share/elasticsearch/data
    networks:
      - elastic          


  es10:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: es10
    mem_limit: 18g
    cpus: 2.0
    environment:
      - node.name=es10
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02,es03,es04,es05,es06,es07,es08,es09
      - cluster.initial_master_nodes=es01,es02,es03,es04,es05,es06,es07,es08,es09,es10
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data10:/usr/share/elasticsearch/data
    networks:
      - elastic



  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.1
    container_name: kibana
    mem_limit: 4g
    cpus: 0.8
    ports:
      - "5601:5601"
    networks:
      - elastic
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200","http://es04:9200","http://es05:9200","http://es06:9200","http://es07:9200","http://es08:9200","http://es09:9200","http://es10:9200"]'
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml

configs:
  kibana_config:
    file: ./kibana/config/kibana.yml


volumes:
  data01:
    driver: local

  data02:
    driver: local

  data03:
    driver: local

  data04:
    driver: local

  data05:
    driver: local

  data06:
    driver: local

  data07:
    driver: local

  data08:
    driver: local

  data09:
    driver: local

  data10:
    driver: local


networks:
  elastic:
    driver: bridge
    external: true
